### ISSUE TITLE
Does not compile or publish

### ISSUE THREAD

**Issue by modist** [Microsoft/kinect-ripple#1]
Hi,

using vs2013 / Kinect v2 - we're not able to compile or publish  the solution. 

It seems that there is a lot of references to files in a non-existing folder 'BinaryOutput'?

**Comment by smarth** [comment]
Hi

Binary Output Folder is created on the fly when you are making the setup for this project.
We can do a skype call to resolve your issue, let me know

Thanks,
Smarth

**Comment by ilijamitkov** [comment]
Hi Smart,

Thank you for your reply, I'm working together with Morten (modist) on kinect and maybe I can give some input regarding this issue .

Unfortunately  BinaryOutput Folder was not created on the fly and the project was not able to build because it was missing artifacts from the Binary Output so we get stuck in this circular reference problem. However we solved the issue by building every project separately and manually moving the artifacts to the  BinaryOutput folder.

The remain problem is missing assets from the Editor project and will appreciate if you make sure that all assets referenced in the project are actually present.

Thank you,
Ilija

**Comment by smarth** [comment]
Hi

I will check things at my end and I will update you on this thread.

Thanks,
Smarth

**Comment by modist** [comment]
thnx - This project has a lot of potential :+1:

**Comment by ilijamitkov** [comment]
Hi,

Is there any update on the above issue?  It looks like nobody works on this project?

Thank you,
Ilija

**Comment by smarth** [comment]
Can you please pull latest changes and try again , I have removed assets that were not required.
Secondly BinaryOutput folder will be made on fly when you build project in release mode , Setup Installer project requires that folder , you can exclude that project if it is not required for you.

Let me know if you are still facing the issue , I will have a call with you to fix it.

Thanks,
Smarth

**Comment by ilijamitkov** [comment]
Thank you Smart,

I downloaded the latest revision and its much better now however there is still some remaining issues

Project RippleEditor

Missing reference Xceed.Wpf.Toolkit
Nuget
Install-Package Extended.Wpf.Toolkit

Project  RippleCommonUtilities

Missing reference AxInterop.ShockwaveFlashObjects
Missing reference Interop.ShockwaveFlashObjects
Cannot find the nuget packages for these missing references.

Thank you,
Ilija

**Comment by smarth** [comment]
https://github.com/Microsoft/kinect-ripple/tree/master/Ripple-V2/Common , there are files here.but they are not referenced in Project.
You should be able to build the project in release mode , I am able to do the same

**Comment by dotslinker** [comment]
Hi Smarth, 
same issue: downloaded, unzipped, tried to compile with VS 2013 with no success, same story with VS 2015 Community Edition. It returns always the same error: 

Error   2   The tag 'ColorPicker' does not exist in XML namespace 'http://schemas.xceed.com/wpf/xaml/toolkit'. Line 34 Position 22. D:\kinect-ripple-master\Ripple-V2\RippleEditor\Controls\FloorPropertiesControl.xaml 34  22  RippleEditor

Any hint welcome!

Paolo

**Comment by abb00sh** [comment]
Hi all, 
I found the same problem when trying to release the project as shown below:

Error 2 The tag 'ColorPicker' does not exist in XML namespace 'http://schemas.xceed.com/wpf/xaml/toolkit'. Line 34 Position 22. D:\kinect-ripple-master\Ripple-V2\RippleEditor\Controls\FloorPropertiesControl.xaml 34 22 RippleEditor

I know you were discussing this about a year ago and maybe you found a solution for this problem. I also contact Smarth about this issue but no reply yet.
I appreciate if you can help me if you find the solution or any useful idea.

I google the error and it show me that need to install Extended WPF toolkit , I did it but the same problem show up.

Abboo

**Comment by smarth** [comment]
Please consider installing appropriate nuget package 'extended wpf toolkit' ,This can solve the issue regarding build with minimal changes.

Please compile in release mode , you should be able to see Binary Output folder in root directory.
You probably do not need setup project unless you want to create an installer.

**Comment by abb00sh** [comment]
Thanks ...I did the same and problem solved. 
I found another problem that maybe some one will face the same problem:

Error   CS0266  Cannot implicitly convert type 'System.Windows.Media.Color?' to 'System.Windows.Media.Color'. An explicit conversion exists (are you missing a cast?)

in  

\kinect-ripple-master\Ripple-V2\RippleEditor\Controls\FloorPropertiesControl.xaml.cs    160 Active

and solve it by just change the line from:
tile.Color = this.clrPicker.SelectedColor;
To
tile.Color = (Color) clrPicker.SelectedColor;

Regards
