### ISSUE TITLE
How to setup ripple?

### ISSUE THREAD

**Issue by Outlaw94** [Microsoft/kinect-ripple#2]
Hey, I'd like to use ripple in my project at HAMK university of applied sciences, but it seems that the .zip doesn't include the .exe file for installation, how do I install it otherwise?
Thanks in advance!

**Comment by smarth** [comment]
This is the source code of ripple ,you have to build the project to use it , you must install required K4W SDK to get started.
In  case you just need an exe and want to build on top of that , let me know your requirements and we can discuss this over a skype call.

**Comment by kulbhushanchand** [comment]
The documentation folder contains a video file showing the installer file. I am searching for the same but unable to find it anywhere.

**Comment by smarth** [comment]
You have to build the project and you can get Ripple executables.

On Wed, Mar 9, 2016 at 3:38 AM, Kulbhushan-Chand notifications@github.com
wrote:

> The documentation folder contains a video file showing the installer file.
> I am searching for the same but unable to find it anywhere.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Microsoft/kinect-ripple/issues/2#issuecomment-194256041
> .

## 

Smarth Behl

**Comment by kulbhushanchand** [comment]
Thanks, but Build results in number of errors.
So, Is it possible to get the executable shown in the video in the documentation folder?

**Comment by smarth** [comment]
Please write an e-mail to smbehl@microsoft.com  regarding your requirement
and what you need to use this project for.
I will help you with executable and some sample applications

On Wed, Mar 9, 2016 at 9:26 PM, Kulbhushan-Chand notifications@github.com
wrote:

> Thanks, but Build results in number of errors.
> So, Is it possible to get the executable shown in the video in the
> documentation folder?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Microsoft/kinect-ripple/issues/2#issuecomment-194677484
> .

## 

Smarth Behl

**Comment by kulbhushanchand** [comment]
I have mailed you. Waiting for your kind reply.

**Comment by smarth** [comment]
The issue was resolved offline
