### ISSUE TITLE
Using two projectors for the floor (WIn 8.1 64)

### ISSUE THREAD

**Issue by dotslinker** [Microsoft/kinect-ripple#3]
Hi all, 
is there a way to use two projectors instead of only one for the floor image? My setup would consist in one front projector and two projectors facing down, closer to the ground. 

Thanks in advance

Paolo

**Comment by TusharChugh** [comment]
Yes, you can use two projectors to project on ground (Floor). I'm assuming that you want to do this to cancel shadows as the projections will overlap. 
You don't need to change any configuration in Ripple to do this. Only you need to duplicate the projection from windows setting which is quite easy.
