### ISSUE TITLE
Where are the installer files shown in the video?

### ISSUE THREAD

**Issue by kulbhushanchand** [Microsoft/kinect-ripple#5]
I was not able to find the KinectRipple installer file as shown in the installation video on the following GitHub page. 
https://github.com/Microsoft/kinect-ripple/tree/master/Documentation

Is the project abandoned as I am not able to track enough progress going on in the same. If not kindly help me with finding the installer file.

**Comment by smarth** [comment]
You have to build the project to get installer files
